name: macos-latest

on:
  push:
    branches: 
    - main
    - dev1.0.0
  pull_request:
    branches:
    - main
    - dev1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --no-fail-fast --all-targets -- --include-ignored
